apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqlight-deployment
  labels:
    app: mqlight
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mqlight
  template:
    metadata:
      labels:
        app: mqlight
    spec:
      containers:
        - name: mqlight
          image: ibmcom/mqlight:1.0
          env:
            - name: LICENSE
              value: accept
          ports:
          - containerPort: 5672
          - containerPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: mqlight
  labels:
    app: mqlight
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 9180
  - name: amqp
    port: 5672
    targetPort: 5672
  selector:
    app: mqlight
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: mqlight
# spec:
#   hosts:
#     - "test.com"
#   gateways:
#   - mqlight-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /
#     route:
#     - destination:
#         port:
#           number: 8000
#         host: mqlight
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: mqlight-gateway
# spec:
#   selector:
#     istio: ingressgateway # use Istio default gateway implementation
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - "test.com"